import type { GridFrame, GridOptions } from '@/entities/sprite/domain'

export const spacedSheet = { name: 'spaced.png', type: 'image/png', width: 114, height: 78 }
export const spacing: GridOptions = { offsetX: 10, offsetY: 8, gapX: 4, gapY: 6 }
export const spacedFrames: readonly GridFrame[] = [
  {
    id: 'grid-10-8-32-32',
    displayNumber: 1,
    row: 0,
    column: 0,
    x: 10,
    y: 8,
    width: 32,
    height: 32,
    selected: false,
  },
  {
    id: 'grid-46-8-32-32',
    displayNumber: 2,
    row: 0,
    column: 1,
    x: 46,
    y: 8,
    width: 32,
    height: 32,
    selected: false,
  },
  {
    id: 'grid-82-8-32-32',
    displayNumber: 3,
    row: 0,
    column: 2,
    x: 82,
    y: 8,
    width: 32,
    height: 32,
    selected: false,
  },
  {
    id: 'grid-10-46-32-32',
    displayNumber: 4,
    row: 1,
    column: 0,
    x: 10,
    y: 46,
    width: 32,
    height: 32,
    selected: false,
  },
  {
    id: 'grid-46-46-32-32',
    displayNumber: 5,
    row: 1,
    column: 1,
    x: 46,
    y: 46,
    width: 32,
    height: 32,
    selected: false,
  },
  {
    id: 'grid-82-46-32-32',
    displayNumber: 6,
    row: 1,
    column: 2,
    x: 82,
    y: 46,
    width: 32,
    height: 32,
    selected: false,
  },
]
